services:
  HomeWork:  # internal service name (must be a valid directory name)
    name: domashkaaa  # pretty name displayed on the checksystem board
    checker:
      basedir: ./checkers/HomeWork  # directory with checkers (relative to services.yml)
      script: ./checker.py  # checker script (relative to checker.basedir); make sure it's executable (chmod +x)
      setup: pip install --break-system-packages certifi==2025.6.15 charset-normalizer==3.4.2 cryptohash==1.0.5 idna==3.10 mpmath==1.3.0 requests==2.32.4 sympy==1.14.0 urllib3==2.5.0 PyYAML==6.0.2 dockerfile-parse==2.0.1
    vuln:
      basedir: ./services/HomeWork  # this folder should contain docker-compose.yml; copied to vulnbox
