services:
  HomeWork:  # internal service name (must be a valid directory name)
    name: domashkaaa  # pretty name displayed on the checksystem board
    checker:
      basedir: ./checkers/HomeWork  # directory with checkers (relative to services.yml)
      script: ./checker.py  # checker script (relative to checker.basedir); make sure it's executable (chmod +x)
      setup: >
        pip install --break-system-packages
        aiofiles==24.1.0
        annotated-types==0.7.0
        anyio==4.9.0
        asttokens==3.0.0
        attrs==25.3.0
        backcall==0.2.0
        bcrypt==4.3.0
        beautifulsoup4==4.13.4
        bleach==6.2.0
        certifi==2025.4.26
        cffi==1.17.1
        charset-normalizer==3.4.2
        click==8.1.8
        colorama==0.4.6
        cryptography==44.0.3
        cryptohash==1.0.5
        decorator==5.2.1
        defusedxml==0.7.1
        dockerfile-parse==2.0.1
        docopt==0.6.2
        executing==2.2.0
        fake-useragent==2.2.0
        fastapi==0.115.12
        fastjsonschema==2.21.1
        gmpy2==2.2.1
        greenlet==3.2.1
        h11==0.16.0
        idna==3.10
        ipython==8.12.3
        jedi==0.19.2
        Jinja2==3.1.6
        jose==1.0.0
        jsonschema==4.23.0
        jsonschema-specifications==2025.4.1
        jupyter_client==8.6.3
        jupyter_core==5.7.2
        jupyterlab_pygments==0.3.0
        MarkupSafe==3.0.2
        matplotlib-inline==0.1.7
        mistune==3.1.3
        mpmath==1.3.0
        nbclient==0.10.2
        nbconvert==7.16.6
        nbformat==5.10.4
        packaging==25.0
        pandocfilters==1.5.1
        parso==0.8.4
        passlib==1.7.4
        pickleshare==0.7.5
        pillow==11.2.1
        pipreqs==0.5.0
        platformdirs==4.3.8
        prompt_toolkit==3.0.51
        pure_eval==0.2.3
        pycparser==2.22
        pycryptodome==3.23.0
        pydantic==2.11.4
        pydantic_core==2.33.2
        Pygments==2.19.1
        PyJWT==2.10.1
        python-dateutil==2.9.0.post0
        PyYAML==6.0.2
        pyzmq==26.4.0
        referencing==0.36.2
        requests==2.32.3
        requests-toolbelt==1.0.0
        rpds-py==0.24.0
        security==1.3.1
        six==1.17.0
        sniffio==1.3.1
        soupsieve==2.7
        SQLAlchemy==2.0.40
        stack-data==0.6.3
        starlette==0.46.2
        sympy==1.14.0
        tinycss2==1.4.0
        tornado==6.4.2
        traitlets==5.14.3
        typing-inspection==0.4.0
        typing_extensions==4.13.2
        urllib3==2.4.0
        uvicorn==0.34.2
        wcwidth==0.2.13
        webencodings==0.5.1
        yarg==0.1.9
    vuln:
      basedir: ./services/HomeWork  # this folder should contain docker-compose.yml; copied to vulnbox
